import Link from 'next/link';
import Image from 'next/image';
import { notFound } from 'next/navigation';
import type { Metadata } from 'next';
import { BLOG_POSTS, getBlogPost } from '@/lib/blog-posts';
import Navbar from '@/components/Navbar';
import BlogScrollTracker from '@/components/BlogScrollTracker';

interface Props {
  params: Promise<{ slug: string }>;
}

export async function generateStaticParams() {
  return BLOG_POSTS.map(p => ({ slug: p.slug }));
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { slug } = await params;
  const post = getBlogPost(slug);
  if (!post) return {};
  const url = `https://presenzia.ai/blog/${slug}`;
  return {
    title: `${post.title} | presenzia.ai`,
    description: post.description,
    alternates: { canonical: url },
    openGraph: {
      title: post.title,
      description: post.description,
      type: 'article',
      publishedTime: post.date,
      url,
      // og:image is auto-generated by opengraph-image.tsx in this directory
    },
    twitter: {
      card: 'summary_large_image',
      title: post.title,
      description: post.description,
      // twitter:image is auto-generated by opengraph-image.tsx in this directory
    },
  };
}

function fmtDate(d: string) {
  return new Date(d).toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' });
}

/** Parse inline markdown: **bold** and [links](url) */
function parseInline(text: string, keyPrefix: string = ''): React.ReactNode[] {
  // First split by bold markers, then handle links within each segment
  const boldParts = text.split(/\*\*(.*?)\*\*/g);
  const nodes: React.ReactNode[] = [];
  let nodeIdx = 0;

  for (let k = 0; k < boldParts.length; k++) {
    const segment = boldParts[k];
    const isBold = k % 2 === 1;

    // Split segment by markdown links [text](url)
    const linkParts = segment.split(/\[([^\]]+)\]\(([^)]+)\)/g);
    // linkParts pattern: [before, linkText, linkUrl, after, linkText, linkUrl, after, ...]

    for (let m = 0; m < linkParts.length; m++) {
      if (m % 3 === 0) {
        // Plain text
        if (linkParts[m]) {
          if (isBold) {
            nodes.push(<strong key={`${keyPrefix}-${nodeIdx++}`} style={{ color: '#F5F0E8' }}>{linkParts[m]}</strong>);
          } else {
            nodes.push(linkParts[m]);
          }
        }
      } else if (m % 3 === 1) {
        // Link text — next part (m+1) is the URL
        const linkText = linkParts[m];
        const linkUrl = linkParts[m + 1] || '#';
        const isInternal = linkUrl.startsWith('/');
        if (isBold) {
          nodes.push(
            <strong key={`${keyPrefix}-${nodeIdx++}`} style={{ color: '#F5F0E8' }}>
              <Link href={linkUrl} style={{ color: '#C9A84C', textDecoration: 'underline', textUnderlineOffset: '2px' }} {...(!isInternal ? { target: '_blank', rel: 'noopener noreferrer' } : {})}>
                {linkText}
              </Link>
            </strong>
          );
        } else {
          nodes.push(
            <Link key={`${keyPrefix}-${nodeIdx++}`} href={linkUrl} style={{ color: '#C9A84C', textDecoration: 'underline', textUnderlineOffset: '2px' }} {...(!isInternal ? { target: '_blank', rel: 'noopener noreferrer' } : {})}>
              {linkText}
            </Link>
          );
        }
      }
      // m % 3 === 2 is the URL, already consumed above
    }
  }

  return nodes;
}

function renderContent(content: string) {
  const lines = content.split('\n');
  const elements: React.ReactNode[] = [];
  let i = 0;

  while (i < lines.length) {
    const line = lines[i];

    // Markdown table detection
    if (line.startsWith('|') && line.includes('|')) {
      const tableRows: string[] = [line];
      while (i + 1 < lines.length && lines[i + 1].startsWith('|')) {
        i++;
        tableRows.push(lines[i]);
      }
      // Filter out separator rows (|---|---|)
      const dataRows = tableRows.filter(r => !/^\|[\s-:|]+\|$/.test(r));
      if (dataRows.length > 0) {
        const headerCells = dataRows[0].split('|').filter(c => c.trim() !== '').map(c => c.trim());
        const bodyRows = dataRows.slice(1).map(r => r.split('|').filter(c => c.trim() !== '').map(c => c.trim()));
        elements.push(
          <div key={i} style={{ overflowX: 'auto', marginBottom: '1.25rem' }}>
            <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '0.9rem' }}>
              <thead>
                <tr>
                  {headerCells.map((cell, ci) => (
                    <th key={ci} style={{ padding: '0.5rem 0.75rem', borderBottom: '2px solid #333', color: '#F5F0E8', fontWeight: 600, textAlign: 'left', whiteSpace: 'nowrap' }}>{parseInline(cell, `th-${i}-${ci}`)}</th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {bodyRows.map((row, ri) => (
                  <tr key={ri}>
                    {row.map((cell, ci) => (
                      <td key={ci} style={{ padding: '0.4rem 0.75rem', borderBottom: '1px solid #1A1A1A', color: '#AAAAAA' }}>
                        {parseInline(cell, `td-${i}-${ri}-${ci}`)}
                      </td>
                    ))}
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        );
      }
      i++;
      continue;
    }

    if (line.startsWith('### ')) {
      elements.push(
        <h3 key={i} style={{ fontFamily: "var(--font-playfair, 'Playfair Display', serif)", fontSize: '1.15rem', color: '#F5F0E8', fontWeight: 600, marginTop: '2rem', marginBottom: '0.5rem', lineHeight: 1.3 }}>
          {parseInline(line.slice(4), `h3-${i}`)}
        </h3>
      );
    } else if (line.startsWith('## ')) {
      elements.push(
        <h2 key={i} style={{ fontFamily: "var(--font-playfair, 'Playfair Display', serif)", fontSize: '1.4rem', color: '#F5F0E8', fontWeight: 600, marginTop: '2.5rem', marginBottom: '0.75rem', lineHeight: 1.3 }}>
          {parseInline(line.slice(3), `h2-${i}`)}
        </h2>
      );
    } else if (line.startsWith('**') && line.endsWith('**')) {
      elements.push(
        <p key={i} style={{ color: '#F5F0E8', fontWeight: 600, fontSize: '1rem', lineHeight: 1.7, marginBottom: '0.5rem' }}>
          {parseInline(line.slice(2, -2), `bold-${i}`)}
        </p>
      );
    } else if (line.startsWith('- ')) {
      const items: string[] = [line.slice(2)];
      while (i + 1 < lines.length && lines[i + 1].startsWith('- ')) {
        i++;
        items.push(lines[i].slice(2));
      }
      elements.push(
        <ul key={i} style={{ paddingLeft: '1.5rem', marginBottom: '1.25rem' }}>
          {items.map((item, j) => (
            <li key={j} style={{ color: '#AAAAAA', fontSize: '1rem', lineHeight: 1.7, marginBottom: '0.4rem' }}>
              {parseInline(item, `ul-${i}-${j}`)}
            </li>
          ))}
        </ul>
      );
    } else if (/^\d+\.\s/.test(line)) {
      // Ordered list
      const items: string[] = [line.replace(/^\d+\.\s/, '')];
      while (i + 1 < lines.length && /^\d+\.\s/.test(lines[i + 1])) {
        i++;
        items.push(lines[i].replace(/^\d+\.\s/, ''));
      }
      elements.push(
        <ol key={i} style={{ paddingLeft: '1.5rem', marginBottom: '1.25rem' }}>
          {items.map((item, j) => (
            <li key={j} style={{ color: '#AAAAAA', fontSize: '1rem', lineHeight: 1.7, marginBottom: '0.4rem' }}>
              {parseInline(item, `ol-${i}-${j}`)}
            </li>
          ))}
        </ol>
      );
    } else if (line.trim() === '') {
      // skip blank lines
    } else {
      // Regular paragraph — handle **bold** and [links](url) inline
      elements.push(
        <p key={i} style={{ color: '#AAAAAA', fontSize: '1rem', lineHeight: 1.75, marginBottom: '1.25rem' }}>
          {parseInline(line, `p-${i}`)}
        </p>
      );
    }

    i++;
  }

  return elements;
}

export default async function BlogPostPage({ params }: Props) {
  const { slug } = await params;
  const post = getBlogPost(slug);
  if (!post) notFound();

  const url = `https://presenzia.ai/blog/${slug}`;
  const wordCount = post.content.split(/\s+/).filter(Boolean).length;
  const blogPostingSchema = {
    '@context': 'https://schema.org',
    '@type': 'BlogPosting',
    headline: post.title,
    description: post.description,
    datePublished: post.date,
    dateModified: post.date,
    wordCount,
    url,
    mainEntityOfPage: { '@type': 'WebPage', '@id': url },
    author: {
      '@type': 'Person',
      name: post.author || 'Presenzia Team',
      url: 'https://presenzia.ai/about',
    },
    publisher: {
      '@type': 'Organization',
      name: 'presenzia.ai',
      url: 'https://presenzia.ai',
      logo: { '@type': 'ImageObject', url: 'https://presenzia.ai/og-image.png' },
    },
    image: `https://presenzia.ai/blog/${slug}/opengraph-image`,
  };

  const breadcrumbSchema = {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: [
      { '@type': 'ListItem', position: 1, name: 'Home', item: 'https://presenzia.ai' },
      { '@type': 'ListItem', position: 2, name: 'Blog', item: 'https://presenzia.ai/blog' },
      { '@type': 'ListItem', position: 3, name: post.title, item: url },
    ],
  };

  return (
    <div style={{ minHeight: '100vh', background: 'rgba(10,10,10,0.97)', fontFamily: 'var(--font-inter, Inter, sans-serif)', position: 'relative', zIndex: 1 }}>
      <BlogScrollTracker slug={slug} title={post.title} />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(blogPostingSchema) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }}
      />
      <Navbar />

      {/* Breadcrumb below navbar */}
      <div style={{ paddingTop: '72px' }}>
        <div style={{ borderBottom: '1px solid #1A1A1A', padding: '0.75rem 2rem' }}>
          <Link href="/blog" style={{ color: '#999', fontSize: '0.8rem', textDecoration: 'none', transition: 'color 0.2s' }}>
            ← All posts
          </Link>
        </div>
      </div>

      <article style={{ maxWidth: '680px', margin: '0 auto', padding: '3rem 2rem 6rem' }}>
        {/* Meta */}
        <div style={{ display: 'flex', gap: '1rem', alignItems: 'center', marginBottom: '1.5rem', flexWrap: 'wrap' }}>
          <span style={{ fontSize: '0.75rem', color: '#C9A84C', letterSpacing: '0.1em', textTransform: 'uppercase' }}>
            {post.category}
          </span>
          <span style={{ fontSize: '0.75rem', color: '#999' }}>{fmtDate(post.date)}</span>
          <span style={{ fontSize: '0.75rem', color: '#999' }}>{post.readTime}</span>
          <span style={{ fontSize: '0.75rem', color: '#999' }}>By {post.author || 'Presenzia Team'}</span>
        </div>

        {/* Title */}
        <h1 style={{ fontFamily: "var(--font-playfair, 'Playfair Display', serif)", fontSize: 'clamp(1.75rem, 4vw, 2.5rem)', color: '#F5F0E8', fontWeight: 600, marginBottom: '1.5rem', lineHeight: 1.2 }}>
          {post.title}
        </h1>

        {/* Hero image */}
        <div style={{
          position: 'relative',
          width: '100%',
          aspectRatio: '1200 / 630',
          marginBottom: '2rem',
          overflow: 'hidden',
          border: '1px solid #1A1A1A',
        }}>
          <Image
            src={post.heroImage}
            alt={post.heroImageAlt}
            fill
            style={{ objectFit: 'cover' }}
            sizes="(max-width: 680px) 100vw, 680px"
            priority
          />
          <div style={{
            position: 'absolute',
            inset: 0,
            background: 'linear-gradient(to top, rgba(10,10,10,0.4) 0%, transparent 40%)',
            pointerEvents: 'none',
          }} />
        </div>

        {/* Description */}
        <p style={{ color: '#999', fontSize: '1.05rem', lineHeight: 1.7, marginBottom: '3rem', borderBottom: '1px solid #1A1A1A', paddingBottom: '2rem' }}>
          {post.description}
        </p>

        {/* Content */}
        <div>{renderContent(post.content)}</div>

        {/* CTA */}
        <div style={{ marginTop: '4rem', padding: '2rem', background: '#111', border: '1px solid #2a2a2a' }}>
          <div style={{ fontSize: '0.75rem', letterSpacing: '0.12em', color: '#C9A84C', textTransform: 'uppercase', marginBottom: '0.75rem' }}>
            Find out where you stand
          </div>
          <p style={{ color: '#F5F0E8', fontSize: '1.05rem', fontWeight: 600, marginBottom: '0.5rem', fontFamily: "var(--font-playfair, 'Playfair Display', serif)" }}>
            Check your AI visibility score, free, in 60 seconds
          </p>
          <p style={{ color: '#999', fontSize: '0.875rem', lineHeight: 1.7, marginBottom: '1.5rem' }}>
            See how ChatGPT, Claude, Perplexity, and Google AI rank your firm right now. No credit card required.
          </p>
          <div style={{ display: 'flex', gap: '1rem', alignItems: 'center', flexWrap: 'wrap' }}>
            <Link href="/score" style={{ display: 'inline-block', padding: '0.75rem 1.75rem', background: '#C9A84C', color: '#0A0A0A', fontWeight: 700, fontSize: '0.875rem', textDecoration: 'none', letterSpacing: '0.02em' }}>
              Get my free score →
            </Link>
            <Link href="/pricing" style={{ color: '#C9A84C', fontSize: '0.85rem', textDecoration: 'none', fontWeight: 500 }}>
              View full audit plans
            </Link>
          </div>
        </div>
      </article>
    </div>
  );
}
